name: Auth tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Step 1 Check version Newman and Node
        run: |
          newman --version
          node --version
            
      - name: Step 2 Install Newman-Reporter-Htmlextra
        run: sudo npm install -g newman-reporter-htmlextra
        
      - name: Step 3 Execute collection
        run: newman run auth_collection.json -e env-QaCoders.json -g env-globals.json --delay-request 1 --reporters cli,htmlextra --reporter-htmlextra-export ./results/Report.html

      - name: Step 4 Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
            name: report
            path: ./results/Report.html